### ISSUE TITLE
Please provide more detailed examples 

### ISSUE THREAD

**Issue by bibinvargheset** [yohplala/oups#9]
i saw your comment on pystore, please provide more detialed exambles for write read and query processinf as well as shed more info by comparing data compression and retrival efficiency tests. it the indexes are adressable it would be good. Quering the full data for informations is also a good feature to see

**Comment by yohplala** [comment]
Hi,

Thanks for your interest in oups.

Both oups and pystore are based on fastparquet engine.
Do not expect performance change when querying or writing data.
ops brings more flexibility to manage duplicates, and will offer you 'convenient' function through `@toplevel` decorator to index your library of dataset.

Please, do check the tests folder to find more examples of how using it.

If documentation is too scarce, please  pinpoint the paragraph that needs more detail, explaining what you see missing, and i will complete it.

Thanks again,
Bests

**Comment by bibinvargheset** [comment]
please checkout examble in pystore it is much more easier to understand. it covers most aspects of pystore. can you please try to create something like that with mutli sublevels and most features pratically expained.

**Comment by yohplala** [comment]
Hi @bibinvargheset 

Please, do you confirm you have been through the documentation already?

> mutli sublevels

You should check the example provided [in this page](https://yohplala.github.io/oups/indexing.html).

> Quering the full data for informations
> ...most features

I do recommend going through all [this page](https://yohplala.github.io/oups/parquetset.html).

Really, I do advice to read the documentation, one page after the other, and playing the example provided, checking what happens on your hard drive.
If more question, I also do recommend reading the docstrings, which can be access also in the documentation, [here](https://yohplala.github.io/oups/api.html).

Please, note, *oups* is not intended to be a clone of *pystore*. Would it have been so, I would have started by forking *pystore*.

What is not stated in the documentation, because I feel it is too abrupt, is that somehow, *oups* intent is to provide some tools for tackling the paradigm of managing data both for training NN, and live data for running trained NN.

In 1st case, you need tool able to manage efficiently large size of data. Parquet format (and fastparquet) is a good base tool for that.
In 2nd case, you need tool able to handle your data as if it is a mutable object. This is the motivation of most of my PRs to fastparquet, providing some features to `ParquetFile` so it can be updated. *oups* then provides more "user-friendly" access to these features.

I hope this clarifies a bit the intent behind *oups*.

Now, like for most machine learning projects I guess, data management is both a base topic and a topic onto which people don't want to spend time...
Because I don't have much time, I will only be able to answer very precise question, and not the general request you submit.
I hope you will understand.

Best regards
